In [ ]:
import sys
import pandas as pd

df = pd.read_csv("dados/IBGE_populacaobrasil_2025.csv")

c:\Users\User\Documents\GitHub\Projeto_Integrador_Django\.venv\Scripts\python.exe
3.0.5

In [3]:
df.head()

     estado  uf    regiao   populacao   ano
0      Acre  AC     Norte     884.372  2025
1   Alagoas  AL  Nordeste   3.220.848  2025
2     Amapá  AP     Norte     806.517  2025
3  Amazonas  AM     Norte   4.321.616  2025
4     Bahia  BA  Nordeste  14.870.907  2025

In [4]:
df.dtypes

estado         str
uf             str
regiao         str
populacao      str
ano          int64
dtype: object

In [5]:
df["populacao"] = (
    df["populacao"]
    .str.replace(".", "", regex=False)
    .astype(int)
)

In [6]:
df.head()

     estado  uf    regiao  populacao   ano
0      Acre  AC     Norte     884372  2025
1   Alagoas  AL  Nordeste    3220848  2025
2     Amapá  AP     Norte     806517  2025
3  Amazonas  AM     Norte    4321616  2025
4     Bahia  BA  Nordeste   14870907  2025

In [7]:
df.dtypes

estado         str
uf             str
regiao         str
populacao    int64
ano          int64
dtype: object

In [8]:
len(df)

27

In [9]:
df["uf"].nunique()

27

In [10]:
df.isnull().sum()

estado       0
uf           0
regiao       0
populacao    0
ano          0
dtype: int64

In [12]:
df.duplicated(subset=["uf", "ano"]).sum()

np.int64(0)

In [14]:
tuple(df.iloc[0])

('Acre', 'AC', 'Norte', np.int64(884372), np.int64(2025))

In [16]:
registros = list(df.itertuples(index=False, name=None))

registros[:3]

[('Acre', 'AC', 'Norte', 884372, 2025),
 ('Alagoas', 'AL', 'Nordeste', 3220848, 2025),
 ('Amapá', 'AP', 'Norte', 806517, 2025)]

In [17]:
type(registros[0][3])

int